name: Pull Request Workflow

on:
  workflow_dispatch:
    inputs:
      release_string:
        description: 'Something'
        required: true
        type: string #integer

jobs:
  triggered_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run a job
        run: echo "Workflow triggered by PR #${{ github.event.inputs.release_string }}"
